### ISSUE TITLE
Address issues raised from external security scan

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#112]
An external security scan showed an issue that could potentially be used to trick users into modifying their data without their consent.

We need to look into this and check if the data can indeed be modified by hand.

The details were shared offline.

**Comment by pengyin-shan** [comment]
Task list based on Kirk's email:

Highest Priority:

- [ ] *the _method function on /plans/<planID> is set to a common verb, PUT, and does not return an error when altered to another, such as DELETE; Is there a way to ensure that this isn't actually deleting plans in the backend?* (In "forced browsing" section of the report) -> make sure the manipulation of the PUT won't affect plan

---

Future Navigation (after 3.0 release)

- [ ] *Samesite, possibly a CSRF token, content security policy (And SRI as a sort of sub-class of that), and secure attribute on cookies could all at some point in the future help to mitigate some as of yet unknown vulnerability as defense in depth* (refer to report for detail)

- [ ] *The "business logic abuse" mentioned with the parameter user on /users seems like a false positive as it just returns a 500 internal server error* -> need verification

- [ ] *Defining the charset is a way to mitigate a very difficult to execute attack involving tricking the browser into interpreting a page, usually with user input, as UTF-7: it's nice to declare it just in case, but this is very difficult to actually accomplish* -> verify, (change?) and document

**Comment by pengyin-shan** [comment]
@lagoan for the first issue (DELETE instead of PUT), we already have a method to make sure that the user is authorized to edit the specific plan in `plan.rb`:
![Screen Shot 2022-01-20 at 18 01 26](https://user-images.githubusercontent.com/92752107/150435757-f017eb07-b85d-47b1-a8bc-626512577a12.png)
So we can conclude that the user who does the DELETE or PUT does have the authentication to do so.

Although both DELETE and PUT are using the same Pundit policy to check eligibility for the specific action:
![Screen Shot 2022-01-20 at 17 58 42](https://user-images.githubusercontent.com/92752107/150435606-fff122be-d88f-4ef7-b1c9-15f9b526a529.png)

but I think for the business logic, it is **OK** for users to use DELETE instead of PUT with a list of parameters (i.e. PUT is changed to DELETE in the request). As long as the user is the authorized user for the plan, the freedom of modifying the verb to something else is on the user's side. But the user also needs to take the responsibility of doing this (which is not possible from the UI side). 

I think it will be interesting to hear UCC's idea about this. We could also choose a more strict approach for this issue (such as forcing more on the difference between DELETE and PUT), but the current behavior also makes sense from the business side.

**Comment by pengyin-shan** [comment]
close this issue for now. Will reopen if Kirk has other requests
