### ISSUE TITLE
Limited support for special characters in DMPs

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#239]
Currently, users cannot create DMPs using characters from the Nsyilxcn and Coast Salish languages (available [here](https://fnel.arts.ubc.ca/resources/font/)).

**Comment by pengyin-shan** [comment]
### First Nations Unicode based on UBC's instruction

I created https://uat.library.ualberta.ca:3000/plans/9355 for `First Nations Unicode Font` only. The font typed into DMP Assistant is based on Mac FNuni_V2.3 Keyboard.

-----

See the 'write plan' section for all test inputs in rick text box. See the 'contributor' section for inputs in regular text box.

-----

Observations based on the current version of the DMP Assistant:

1. All characters can show in the rich text editor (except one character that's due to the keyboard. See 10)

2. All characters can show in the regular text box. I use the 'Contributor' section to test:
<img width="931" alt="Screenshot 2022-10-27 at 4 23 54 PM" src="https://user-images.githubusercontent.com/92752107/198390671-a69e769a-91b6-4007-8703-c27ea025b273.png">

3. PDF download (same behavior for all fonts):
3.1 one character doesn't display well:
<img width="634" alt="Screenshot 2022-10-27 at 3 58 10 PM" src="https://user-images.githubusercontent.com/92752107/198386466-8a04039f-4f46-4a2a-9e35-a5e529b458e2.png"> 3.2 A few empty spaces are filled after download:
<img width="256" alt="Screenshot 2022-10-27 at 4 01 49 PM" src="https://user-images.githubusercontent.com/92752107/198386998-2af50b71-c716-4a04-858f-61bda796d4fb.png">

4. HTML download: lots of characters have problems in Chrome but not in Firefox

5. CSV download: based on which application users are using to open it, user can see totally different characters (for example, Excel and TextEdit display absolutely different characters)

6. DOCX download: after changing to First Nation Code in Word, 2.2 problem appears again (empty spaces are filled)

7. TEXT download: opened using TextEdit and see problem 2.2

8. JSON download (with all special characters displaying as contributor name): JSON string is ok, but users might see the wrong display if they open JSON file using different applications

9. There's one character that Mac Mac FNuni_V2.3 Keyboard cannot type:<img width="292" alt="Screenshot 2022-10-27 at 3 42 18 PM" src="https://user-images.githubusercontent.com/92752107/198385895-61900f15-c0cf-4664-a8bf-b98a7b8b55db.png">

-----

**Generally, the current version of DMP Assistant supports the entering and saving of First Nation Unicode Font, but downloading could have issues**. Meanwhile, if the third-party application to download DMP provides bad font support, the user also gonna see the wrong character displayed even if the downloaded file is correct.

---

@isawil  you can update the information above to the UBC team and see if they are ok with the current version. It gonna take a very long time to fully support this font since we have limited resources. However, a walkaround is to download a WORD file and search for problematic characters then replace them with the correct ones. From our test, we can provide a list of characters that needs extra attention.

**Comment by pengyin-shan** [comment]
I'm going to do the same test for Omar's plan now (plan 9353 with all characters and other special characters) and update the result here. 

Meanwhile, @isawil please test plan 9355 using a windows input (_since I don't have windows machine_) and let me know if you see a difference result.

**Comment by shilowil** [comment]
When you have time, could you repeat the tests you performed before? I'm interested in seeing whether the recent fix will change the outcome.

**Comment by pengyin-shan** [comment]
> When you have time, could you repeat the tests you performed before? I'm interested in seeing whether the recent fix will change the outcome.

Did they release a new version of the keyboard? I currently have Mac FNuni_V2.3

**Comment by shilowil** [comment]
I don't believe so -- I'm more interested in whether we will be able to export PDFs with FNUF characters in them now that we have fixed the previous special characters issue.

**Comment by pengyin-shan** [comment]
> 

No, the last release didn't impact the download result. So for those characters which won't display well, their condition stays the same.

**Comment by shilowil** [comment]
Thanks for checking! I'd like us to fix this when we can -- are we waiting on an updated keyboard?

**Comment by pengyin-shan** [comment]
We will need to wait for Mac FNuni_V2.3 (or Windows version) to update first.

**Comment by pengyin-shan** [comment]
@isawil : I don't have time to work on this issue, since this looks like a long-term development feature. You can resume the navigation after we have more clear plan on this

**Comment by lagoan** [comment]
The problematic characters are from a simpler group (for example quotation marks). We can return to this issue at a later time if needed.
