### ISSUE TITLE
3.1.0 UAT Testing

### ISSUE THREAD

**Issue by pengyin-shan** [portagenetwork/roadmap#298]
@isawil UAT at https://uat.library.ualberta.ca:3000/ is ready for testing. Please navigate thoroughly and list anything you feel is different from current production here, so I can go through them and decide if I'm going to do an immediate fix, or push it later to the post-3.1.0 minor release.

For your reference:

1. The data is slightly different from the production server's data since I used a snapshot of the current database on Dec 2022. If you see significant data difference, let me know and I'll check it

2. Please test both the English and French versions. If any places are missing translation, I'll check it.

3. Please note logo images are mostly missing because image storage settings are different in UAT. You can test logo updates though. Just remember every time I redeploy the UAT version, all images will be erased.

4. Please ignore the `Run your own filter` part on the statistics page for now. I'm navigating why it doesn't generate correct statistics. 
- [x] #299

5. For the 3.1.0 feature specifically, you can refer to my personal worksheet ([issues.xlsx](https://github.com/portagenetwork/roadmap/files/10387260/issues.xlsx)) at tab 3 `3.1.0-feature`. *Just test the yellow ones, such as the Research Output row below*. Blues are code-side changes that you can ignore. 
![Screenshot 2023-01-10 at 5 25 39 PM](https://user-images.githubusercontent.com/92752107/211675422-f0a0aca0-64b1-44ae-86f1-b6634cb5c0b0.png)

6. I am constantly debugging on my side, *so please wait a bit if you see UAT is not available*. It is highly possible that I am uploading a new version. If you still see a long outage, slack me and I'll update you.

-----
I plan to do a quick minor release right after this large 3.1.0 release for bug fixes. For the 3.1.0 release, let's target the end of Jan. Thus *we will want to finish UAT testing in one week*. If you have any questions, pls let me know.

**Comment by shilowil** [comment]
Thanks, Wendy! Here is what I have noticed:

1. When searching for primary research organization (on the "Create a new plan" page), cégeps do not show in results when searching using "cegep" (without the accented character). I believe that currently, searching for "cegep" also returns "cégep" results. The same problem exists with "université" results when searching for "universite." 
2. However, when selecting contributor affiliations in the "Contributors" tab of a plan, this issue does not exist (although searching for "universite" also returns results for "university"). However, unmanaged organizations appear in search results for contributor affiliation.
3. When creating a plan and viewing the site in French, the comments and guidance tab button is untranslated and appears as "Comments & Guidance."
4. There are a few areas in the "write plan" page that have unexpected text in the text box. This problem is in both the English and French versions. In the preservation section of the template, this text appears:
![image](https://user-images.githubusercontent.com/30664432/211861733-91a4433e-d25c-4c50-8a10-e17f9741c92c.png)

In the "Ethical and Legal Compliance" section as well:
![image](https://user-images.githubusercontent.com/30664432/211866011-f9572abd-4976-4705-8e2f-ad6cd0873b37.png)

And here, in the storage section:
![image](https://user-images.githubusercontent.com/30664432/211866314-fef99027-07ce-4cbd-b456-9f93972ef876.png)

As well as the documentation and metadata section:
![image](https://user-images.githubusercontent.com/30664432/211866557-85b737c7-6b71-4b63-8e35-b801de2bb8ec.png)

The same text also appears in the last two questions in the data collection section.

I am headed to lunch, but will post more findings later!

**Comment by pengyin-shan** [comment]
@isawil Ah sorry I forgot to mention. When you test, can you divide *what's existing in both the current version and UAT version*, and *what's only in UAT version*?

For the UAT test of the 3.1.0 release, I will only fix the bug that reflects **only in UAT but not in current production**. For all issues that exist in both production and UAT, they are old bugs and I'll do a later release for them.

**Comment by shilowil** [comment]
Ah, thanks! I'll go through my notes and note what only exists in UAT.

**Comment by shilowil** [comment]
After reviewing, I can confirm that only items 3 and 4 are outstanding.

**Comment by pengyin-shan** [comment]
Item 3: the translation for `dmp-assistant-test` is ready:https://translation.io/ualbertalib/dmp-assistant-test/fr-CA?segment=161fe6ed&query=Comments%20%26%20Guidance
for `dmp-assistant` (i.e. production version), the 3.1.0 will be released first, then we can add the corresponding translation to translation.io repo

Item 4: I checked the template (which defines the default answer) in https://uat.library.ualberta.ca:3000/org_admin/templates/3536/phases/3528/edit and I found these codes are pre-filled answers. Can you remove them and try again?

BTW, I'll put unmanaged org fixes to the release after 3.1.0, so pls ignore it if you see any unmanaged org appear in the drop-down.

**Comment by shilowil** [comment]
I've gone through the issues spreadsheet you linked, and checked all issues highlighted in yellow. Everything is working as it should aside from issue 22, where the phone number field is still displaying on the add contributor page.

I checked on the pre-filled answers in the write plan page, and can confirm they are gone after deleting the text.

**Comment by pengyin-shan** [comment]
> I've gone through the issues spreadsheet you linked, and checked all issues highlighted in yellow. Everything is working as it should aside from issue 22, where the phone number field is still displaying on the add contributor page.
> 
> I checked on the pre-filled answers in the write plan page, and can confirm they are gone after deleting the text.

Ops sorry my fault. I set `config.x.application.display_contributor_phone_number = true` which opens the phone number field. I have turned it off. If we want to use this field in the future, we can just set it on again.

**Comment by pengyin-shan** [comment]
@isawil : I fixed the filter on the statistics page. Now you can test `https://uat.library.ualberta.ca:3000/usage` as well.

Also, what's the process of overall UAT test?

**Comment by shilowil** [comment]
Thanks, Wendy! I anticipate completing the UAT test by the end of the day tomorrow.

**Comment by pengyin-shan** [comment]
@isawil just want to check the process of uat test, also may I confirm that can you open the uat site as before?

**Comment by shilowil** [comment]
The UAT test is complete! Apologies for not noting it sooner. I'm getting a 502 error when trying to open the UAT site.

**Comment by pengyin-shan** [comment]
> The UAT test is complete! Apologies for not noting it sooner. I'm getting a 502 error when trying to open the UAT site.

Awesome, don't worry I'm fixing the uat site now. Great to see the test complete...no other errors right?

**Comment by pengyin-shan** [comment]
And UAT site is back.

**Comment by shilowil** [comment]
Thanks, Wendy! No other errors, no.

**Comment by pengyin-shan** [comment]
> Thanks, Wendy! No other errors, no.

Awesome, thank you!

**Comment by pengyin-shan** [comment]
Close 3.1.0 testing. Prepare for formal release now.
