### ISSUE TITLE
Translations rake task extremely inefficient

### ISSUE THREAD

**Issue by nmacgreg** [portagenetwork/roadmap#313]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

- RPM: dmp-3.1.0-4.x86_64
- Tag: 3.1.0+portage-3.1.0-alpha.3

**Expected behaviour:**
Low memory usage and low CPU usage, when not under load from web traffic.

**Actual behaviour:**
In our Staging environment, we are running `rake translations:sync`every 5 minutes.   I found the system sluggish at echoing my keystrokes in a terminal, using 75% *of swap*, and a high CPU load average.  Multiple copies of the rake task were running

**Steps to reproduce:**
Just login to Staging - it does this all the time.

To confirm that this cronjob is causing the trouble, last nigh I disabled the crontab & rebooted the system to begin anew without any swap usage.  This morning, it had a very low cpu-load-avg, and had only used ~1/3 of memory.  I ran at the cmdline, copied from the crontab: 

```
[root@southampton ~]# cd /var/www/sites/dmp && RAILS_ENV=staging && GIT_DISCOVERY_ACROSS_FILESYSTEM=1 bundle exec rake translation:sync >> /tmp/translation.log 2>&1
```
Initially, for at least 5 minutes, the single process was pinned at 100% of a single CPU.  Afterwards, it seemed to enter a second phase, where the process uses only 3-5% of a CPU, but maybe it's multithreaded, because the loadavg varies from 2-5 (on a 4-CPU VM)
...and it's still running, more than 25 minutes later, and has *used 75% of swap*!

**Comment by nmacgreg** [comment]
Updated: using all of RAM & all of swap - I think the rake task will crash (?) when it runs out of memory
![image](https://user-images.githubusercontent.com/3227828/218135851-93ae219c-3c29-4392-a3ba-2fd0ad40b347.png)
![image](https://user-images.githubusercontent.com/3227828/218137009-2a253333-5bec-4f9e-87fa-3452c4bf9cf5.png)

A peek at Netdata is instructive: http://southampton:19999

**Comment by nmacgreg** [comment]
I didn't find the logged output of this command very useful, but perhaps you will, Wendy:

```
[root@southampton ~]# cat /tmp/translation.log 
* Downloading YAML source editions.
* Applying YAML source editions.
* Extracting source fields from database.
* Updating POT file.
Warning: The empty "" msgid is reserved by gettext. So gettext("") doesn't returns empty string but the header entry in po file.
```

(as yet incomplete - it's still running, 35 minutes now)

**Comment by nmacgreg** [comment]
I don't feel comfortable taking this into Production. 
If we do, obviously `translations:sync` isn't going to run from cron every 5 minutes - I might run it *once* from the cmdline...

**Comment by nmacgreg** [comment]
I don't often look at the Staging copy of Nagios, but in this case, it's happily reporting trouble: 
![image](https://user-images.githubusercontent.com/3227828/218138793-17a8b0b9-3c20-4809-ac57-e657e927b8fb.png)


Nagios does keep historic performance data, so I can supply: 
![image](https://user-images.githubusercontent.com/3227828/218139372-1fa3c1f1-b315-4a6a-bb11-c00a0ee50271.png)
I used some internal tools to track the latest start of the CPU performance problem to Friday, February 3 @ 4pm -- which corresponds exactly to the date I installed 3.1.0-alpha.3 (you might remember - the day we first got a working version!)

Notice there's an earlier spike in CPU traffic - that starts Mon, Jan 30, 10am.  That's when I began this migration project in earnest.
It ends Tuesday, Jan 31, about 13:26. 
I found this in cmdline history, on my desktop : 

```
 9925  2023-01-31 13:20:26 time ansible-playbook dmp.yml -i ../../inventory-test  --vault-password-file ~/ansible.passwd --tags pg-12-rolling-client 
```

... which means, the initial performance problem stopped the moment I got the PostgreSQL client code installed for the first time.

**Comment by pengyin-shan** [comment]
@nmacgreg Thank you! I just finished the test on uat, which again took around 15 mins, definitely longer than before using PostgreSQL. Since I also have the MariaDB still install on uat, I'll turn db connection back and try a sync using mariaDB, without the 4 rake tasks loaded. I'll see if the problem comes again or not. If not, then the issue is either the 4 rake tasks (which did load many records from external API), or PostgreSQL side

**Comment by pengyin-shan** [comment]
Update on debugging: 

1) tried the main codebase 3.1.1 version (which doesn't include the translation-side of change from 3.1.0) with MySQL(not compatible with MariaDB), with both the original translation.io gem and our modified translation.io gem. No long-time problem was noticed.

2) tried the UAT 3.1.0 version with MariaDB, see a similar long-term issue (~15 mins). 

3) tried the local version with PostgreSQL, and see a similar long-time problem (a bit faster than uat). switch back to MySQL, see a similar long-term issue.   

Thus, I expect the problem is coming from the code side. Navigating it

**Comment by pengyin-shan** [comment]
Checking on 3.0.4 version (current production version), but use MySQL instead. (12:19 start). It got the same complaint as PostgreSQL:

<img width="518" alt="Screenshot 2023-02-10 at 12 17 08 PM" src="https://user-images.githubusercontent.com/92752107/218155527-c3e84d8a-c130-4f0d-b7d9-2f1ddb721723.png">

After I fixed it by commenting out the ` default_scope { order(number: :asc) }` in phase, question and section, it runs well and fast. 

------
Noticed a message that ONLY in 3.1.0 and 3.1.1 (main code):

<img width="322" alt="Screenshot 2023-02-10 at 12 36 10 PM" src="https://user-images.githubusercontent.com/92752107/218158514-98f31fd7-9e97-4848-a402-ca25bb233091.png">

However, 3.1.1 run faster than 3.1.0, even with this message...Gonna to continue to see if any missing `('')` is not caught

**Comment by pengyin-shan** [comment]
removed the parts that generate the warning message. See a reduced time, but the step of updating POT file (the necessary) still can take 4.5 min locally. However, considering that the research output tab is a new feature that needs translation, will check if 5 min now is the necessary time that we need to admin.

**Comment by pengyin-shan** [comment]
Hi @nmacgreg , I tried to adjust some translation settings and push in code in branch issue313. This is what I found when running from my local machine (uat has docker so I cannot use its memory checking):

at the beginning of sync:
<img width="713" alt="Screenshot 2023-02-13 at 11 28 52 AM" src="https://user-images.githubusercontent.com/92752107/218523413-28e0a8bb-221f-44c7-a03c-0bbb70adbc49.png">
<img width="621" alt="Screenshot 2023-02-13 at 12 09 25 PM" src="https://user-images.githubusercontent.com/92752107/218525925-87b26140-daa1-48d1-b47c-ca8f259014ba.png">

in the sync stage that took the longest (_generate POT file_):
<img width="742" alt="Screenshot 2023-02-13 at 11 29 34 AM" src="https://user-images.githubusercontent.com/92752107/218523556-656de902-26b5-4846-bf03-a33290633a56.png">
<img width="615" alt="Screenshot 2023-02-13 at 12 10 02 PM" src="https://user-images.githubusercontent.com/92752107/218525910-e3f7b83c-973f-4998-8ce8-ab727883137d.png">


after sync:
<img width="658" alt="Screenshot 2023-02-13 at 11 32 55 AM" src="https://user-images.githubusercontent.com/92752107/218523607-235d41b1-9d9a-4c6f-99ce-504bebd7b96f.png">
<img width="602" alt="Screenshot 2023-02-13 at 12 13 48 PM" src="https://user-images.githubusercontent.com/92752107/218525887-bc107ffb-c821-49af-82fb-616e2d5c3f2a.png">

So what I found is that:
1) the total time took around 5-8 mins because we need to translate some new features that were added in 3.1.0. We need to adjust our translation frequency in the production server
2) The memory usage is high for a while (19.XXGB most, never exceeding 20GB  w/basic usage took around 9-12 GB). But it dropped soon and return to normal after the sync process. Swap memory never got used.
3) CPU could also see a pike during the sync, but it returns back to normal after the finish

Do you think this is acceptable? I'm ready to release this version for you to test on staging.

**Comment by pengyin-shan** [comment]
Fixed issue in PR 318 (https://github.com/portagenetwork/roadmap/pull/318).
