### ISSUE TITLE
Missing front end French translations

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#404]
For all missing translations not included in #388 

**About Us**

1. "If you have an account please sign in and start creating or editing your DMP. If you do not have a Assistant PGD account, click on [Sign up](https://uat.library.ualberta.ca:3000/) on the homepage. Please visit the [Aide](https://uat.library.ualberta.ca:3000/help) page for guidance."

**Help**

1. "If you need assistance in developing your data management plan, the following resource may help get you started:[ How to manage your dataS’ouvre dans une nouvelle fenêtre](https://portagenetwork.ca/fr/outils-et-ressources/assistant-pgd/comment-gerer-vos-donnees/). If you require more guidance, contact us at [support@portagenetwork.ca](mailto:support@portagenetwork.ca?Subject=Commentaires%20de%20l'Assistant%20PGD)."

**My Dashboard**

1. Text displays in English after logging in -- users must re-select their language as French, after which, French translation will appear.

**Edit my profile**

1. Under the API Access tab, "Regenerate token" appears in English.

**Themes** (superadmin access)

1. Half of the guidance text is in English, and half is in French.

**API Clients** (superadmin access)
1. "Manage API access for external applications"
2. "Create Api Client"

**Project details** (in plan)
1. "Research domain" and its dropdown menu are in English

**Research outputs** (in plan)
1. "Type" dropdown menu
2. "Add a repository" menu: dropdown menu untranslated, as is the text "Repository search"
3. "Metadata standards" menu: displays text as "tous les 9 metadata standards" ("metadata standards" should be translated); header "metadata search" also displays in English
4. Licenses search -- last option ("Other licenses - will load a complete list") 
5. Initial access level dropdown menu

@lagoan -- tagging for you to triage!

**Comment by lagoan** [comment]
@aaronskiba please take a look at these missing French translations and identify them on translation.io as we discussed this morning. 

Let us know if you have any problems

**Comment by aaronskiba** [comment]
## About Us
1. Translation exists if I just add a comma after "If you have an account" (I think adding the comma is correct grammar?)
  - <img width="557" alt="Screenshot 2023-07-28 at 1 07 45 PM" src="https://github.com/portagenetwork/roadmap/assets/71047780/b95ec895-c81d-46ec-aac5-8a5dcd67fdad">

   - A related issue has been created here: #407

## Help
1. This text was modified to address https://github.com/portagenetwork/roadmap/issues/339. A new translation will be needed (**Missing** tag added in Translation.io).

## My Dashboard
1. This may be due to the user's language in **Edit Profile** (e.g. If I set Language to English in Edit Profile, then no matter what the language is set to before I sign in, it will be automatically set to English immediately after I sign in)

## Edit my profile
1. Translation is needed for "Regenerate token" (**Missing** tag has been added in Translation.io)

## Themes (superadmin access)
1. The **Guidelines** entry for **Preservation** translates successfully when a period is added at the end of the English sentence. But rather than the codebase, this change has to be performed in the web app.

## API Clients (superadmin access)
1. "Manage API access for external applications" needs to be re-formatted in codebase `<p>Manage API access for external applications</p>`
2. "Create Api Client" needs to be translated in translation.io (Added a **Missing** tag)

## Project details (in plan)
1.
    - Translation needs to be provided in Translation.io for "Research domain" title (**Missing** tag has been added)
    - Dropdown elements are neither present in Translation.io or the codebase. Rather, they are stored in the `research_domains` db table. The labels associated with these rows will have to be uploaded to Translation.io.

## Research Outputs (in plan)
1.
    - Some translations are missing in Translation.io; **Missing** tag has been added for these.
    - Other translations (e.g. "Text" and "Other") do exist, but the French translations don't seem to be rendering in the dropdown; this will have to be investigated.
    - The file, `app/views/translation_io_exports/_research_output.erb` will need to be modified so its strings are no longer in the underscore format.
2.
    - The dropdown elements do not exist in Translation.io. The selectable subjects strings must be edited in the codebase (`app/presenters/research_output_presenter.rb`).
    - "Repository search" currently exists in Translation.io. However, it exists as "%{topic} search" in the codebase. **Missing** tag has been added to "Repository" and "%{topic} search" Translation.io. (I think this should solve the problem?)
    - (Additional bug noticed while I was testing) "- Enter a search term %{examples} -" is missing a translation. (Added **Missing** tag in Translation.IO). However, %{examples} exists in `app/views/research_outputs/repositories/_search.html.erb` and needs to be edited to allow for Translation.io upload.
    - (Additional bug noticed while I was testing) "Select a subject area to refine your search." (hint when you hover over "- Select a subject area -" is missing a translation (**Missing** tag has been added to translation.io)
3. "Metadata standards" menu:
    - The "tous les 9 metadata standards" text doesn't seem to replicate on my end; am I looking in the correct place?
    - <img width="485" alt="Screenshot 2023-07-31 at 12 26 01 PM" src="https://github.com/portagenetwork/roadmap/assets/71047780/71d463d5-157a-48c8-91a3-0fe6e487b013">
    - Header translation is missing. Same issue as with "Repository search" (see Research Outputs 2.) However, "Metadata Standard" needs to be uploaded to translation.io
4. String not included in Translation.io. The file, `app/views/research_outputs/licenses/_form.html.erb` will have to be modified to enable the upload to Translation.io.
5. Strings not present in Translation.io. Is a corresponding .erb file needed for `enum access` in `app/models/research_output.rb`?

**Comment by lagoan** [comment]
@aaronskiba fixed this.
