### ISSUE TITLE
Ampersand not displaying correctly

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#473]
A user created a DMP and used an ampersand in the title; however, the ampersand is now displaying as "amp;" following the ampersand. I will send the plan ID in a DM.

**Comment by aaronskiba** [comment]
Rather than `&`, Plan.title and Plan.description are both saving `&amp;` to the db. However, unlike Plan.title, Plan.description displays the `&` symbol when rendered. So we should be ok with how we're saving `&` to the db.

The problem appears to be that we are applying `sanitize()` to Plan.description, but not to Plan.title.

**Comment by aaronskiba** [comment]
This Plan.title rendering issue occurs in a few different places.

- Title tag in multiple browser tabs:
  ![Screenshot from 2023-10-10 14-00-08](https://github.com/portagenetwork/roadmap/assets/71047780/6cb70429-35f2-41b2-8288-4514da6e08eb)
- Titles of multiple pages:
  ![Screenshot from 2023-10-10 14-01-33](https://github.com/portagenetwork/roadmap/assets/71047780/3bfdabe6-131d-4ba8-a3fd-53523d0f9057)
- Coversheet
  ![Screenshot from 2023-10-10 14-03-44](https://github.com/portagenetwork/roadmap/assets/71047780/00f8d3fe-1038-409a-a5c2-da779c4c5723)
- Listed plans
  ![Screenshot from 2023-10-10 14-18-48](https://github.com/portagenetwork/roadmap/assets/71047780/c752c2bc-3bad-4b40-b0ad-a32a507d9e01)
