### ISSUE TITLE
Update email address on password reset email

### ISSUE THREAD

**Issue by shilowil** [portagenetwork/roadmap#534]
The current password reset email sent to users contains our previous support email address (support@portagenetwork.ca). Could we update it to the current email address (dmp-assistant@tech.alliancecan.ca)? 

Tagging @lagoan for triage

**Comment by aaronskiba** [comment]
Rather than an issue in the codebase, it looks like the organisation details need to updated within the app itself.

Unfortunately, I'm getting this error when I attempt to update the contact email within the app. Uploading a logo might fix it. But perhaps we should allow for updates without requiring an org to re-upload a logo?

![Screenshot from 2023-11-17 10-29-04](https://github.com/portagenetwork/roadmap/assets/71047780/66756529-5f78-4621-bae2-67ee19be7a62)
![Screenshot from 2023-11-17 10-36-55](https://github.com/portagenetwork/roadmap/assets/71047780/7162c6ab-1018-48c9-9653-010ebddd69bc)

**Comment by aaronskiba** [comment]
After adding a new logo on my local instance, I was able to update the email. It looks like we'll have to add a logo for the Portage Network organisation before we can update other details.
![Screenshot from 2023-11-17 10-55-04](https://github.com/portagenetwork/roadmap/assets/71047780/a168a632-7e95-4634-834a-76c870013600)

**Comment by aaronskiba** [comment]
Editing an organisation used to throw a 500 error, but [that issue](https://github.com/portagenetwork/roadmap/issues/327) was addressed.

Should this be further addressed? Specifically, should an organisation facing this logo issue be able to be edited without having to re-upload their logo?
